spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/distance_calculator
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        ddl-auto: auto
        show_sql: true


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  liquibase:
    change-log: classpath:liquibase/liquibase.yaml
    enabled: true
    url: jdbc:mysql://localhost:3306/distance_calculator
    driver-class-name: com.mysql.cj.jdbc.Driver
    user: root
    password: root
    database-change-log-lock-table: mychangeloglocktable